### ISSUE TITLE
Breaking at React router DOM

### ISSUE THREAD

**Issue by SatyaQworks** [sshyam-gupta/react-router-prompt#38]
: navigator.block is not a function  at use-blocker.ts:13:1

**Comment by SatyaQworks** [comment]
react-router-dom: v6.4.1

**Comment by reintroducing** [comment]
this will not work with react-router v6.4x because they removed the APIs necessary for this solution to work in v6.4.0. There is a pretty lengthy thread about this [here](https://github.com/remix-run/react-router/issues/8139).

**Comment by TrejGun** [comment]
that still works with 
https://github.com/remix-run/react-router/issues/8139#issuecomment-1023105785
and 
```
import { FC } from "react";
import { unstable_HistoryRouter as HistoryRouter } from "react-router-dom";
import { history } from "history";


const App: FC = () => {
  return (
    <HistoryRouter history={history}>
      <YOUR CODE HERE>
    </HistoryRouter>
  );
};

export default App;
```

**Comment by sshyam-gupta** [comment]
I will check this issue this weekend

**Comment by sshyam-gupta** [comment]
https://github.com/remix-run/react-router/issues/8139#issuecomment-1302822885

Will wait for usePrompt and useBlocker to come back in the next release.

**Comment by karol-majewski** [comment]
FYI: `useBlocker` is now available in React Router 👏

**Comment by sshyam-gupta** [comment]
@karol-majewski thanks for heads-up, will create an update.

**Comment by sshyam-gupta** [comment]
Updated with react-router-prompt v0.5.0. 

Note: This supports react router dom >=v6.7.0 and supports only [**data routers**](https://reactrouter.com/en/6.8.1/routers/picking-a-router#using-v64-data-apis)
Do reopen if you find any issue in the release
